Fixing app stopping

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
-set -x
+
 NGINX_VERSION="1.4.4"
 NGINX_BIN_DIR=$OPENSHIFT_ROK4_DIR/usr/nginx/versions/$NGINX_VERSION/bin
 NGINX_EXEC=$OPENSHIFT_ROK4_DIR/usr/nginx/versions/$NGINX_VERSION/bin/nginx
@@ -40,8 +40,8 @@ function start() {
         # nginx will always use the prefix defined at compile time unless an absolute path to the conf file is given
         nohup "$NGINX_EXEC" -c "$NGINX_CONFIG_FILE" 2>&1
         [ "$?" == "0" ] && wait_for_pid_file $NGINX_PID_FILE
-        nohup "$ROK4_EXEC" -f "$ROK4_CONFIG_FILE" 2>&1 &
-        [ "$?" == "0" ] && wait_for_pid_file $ROK4_PID_FILE
+        nohup "$ROK4_EXEC" -f "$ROK4_CONFIG_FILE" > /dev/null 2>&1 &
+        #[ "$?" == "0" ] && wait_for_pid_file $ROK4_PID_FILE
 
     else
         echo "WARN: Could not find the compiled application versions/$NGINX_VERSION/bin/nginx, will not start"
@@ -63,6 +63,9 @@ function stop() {
         pid=`cat "$ROK4_PID_FILE" 2> /dev/null`
         kill $pid
         wait_for_stop $pid
+    else
+        killall rok4
+        [ "$?" == "0" ] || echo "rok4 could not be stopped"
     fi
 }
 
